version: '3.8'

services:
  app-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./db/test.db  
    volumes:
      - ./db:/app/db
